config/routes.rb
SeatSeller::Application.routes.draw do
  devise_for :users

  devise_scope :user do 
    get 'sign_up' => 'devise/registrations#new'
    delete 'sign_out' => 'devise/sessions#destroy'
    get 'sign_in' => 'devise/sessions#new'
  end

  resources :fares, only: :update
  resources :trips do 
    resources :fares, only: :create
  end



  root to: 'trips#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
        can :manage, Trip do |a_trip|
            a_trip.owner == user
        end
        can :request, Trip do |a_trip|
            a_trip.available_seats > 0 && !a_trip.passenger_ids.include?(user.id)
        end
        cannot :request, Trip do |trip|
            trip.owner == user
        end
        can :approve, Fare do |fare|
            !fare.approved?
        end
    end
    can :read, Trip

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/fare.rb
class Fare < ActiveRecord::Base
	#fare tracks the association between trip and passenger
	belongs_to :trip
  belongs_to :passenger, class_name: "User", foreign_key: :passenger_id

  delegate :email, to: :passenger

  scope :pending, where(approved: false)

  def approve!
  	self.approved = true
  	trip.approve_fare(self)
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :destination, :title, :start, :available_seats, :departure_time
  
  scope :available, where('available_seats > 0')

  #trip has an owner
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  #trip has many fares
  has_many :fares, dependent: :destroy
  #trip has many passengers, through fares, when the fares are approved
  has_many :passengers, 
  	through: :fares,
  	class_name: "User",
  	conditions: {'fares.approved' => true}
	has_many :requests, 
		through: :fares, 
		class_name: "User",
		source: :passenger, 
		conditions: {"fares.approved" => false}

		delegate :email, to: :owner

	def add_fare(fare) #requester is the requesting user
		self.fares << fare
	end

	def approve_fare(fare)
		return false unless available_seats > 0 
		fare.save
		self.available_seats -= 1
		save
	end

	def passenger_ids
		#return an array of ids for passengers
		fares.map { |f| f.passenger_id  }
	end

	def approved?
		approved
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  #seller has trips, trips have fares
  has_many :trips

  #buyer has many fares
  has_many :fares, foreign_key: :passenger_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fares_controller.rb
class FaresController < ApplicationController
	before_filter :authenticate_user!
	respond_to :html

	#POST /trips/:trip_id/fares
	def create
		@trip = Trip.find(params[:trip_id])
		authorize! :request, @trip
		flash[:notice] = 'Seat Request Created' if @trip.add_fare(current_user.fares.create)
		respond_with @trip
	end

	#PUT /fares/:id
	#this action approves the fare
	def update
		@fare = Fare.find(params[:id])
		authorize! :manage, @fare.trip
		flash[:notice]='Fare approved' if @fare.approve!
		redirect_to :back 
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  respond_to :html
  def index
  	@trips = Trip.all
  	respond_with @trips
  end

  def show
  	@trip = Trip.find(params[:id])
  	respond_with @trip
  end

  def new
  	@trip = Trip.new
  end

  def create
  	@trip = current_user.trips.build(params[:trip])
  	flash[:notice] = "Trip created" if @trip.save
  	respond_with @trip
  end

  def edit
  	@trip = current_user.trips.find(params[:id])
  	respond_with @trip
  end

  def update
  	@trip = current_user.trips.find(params[:id])
  	flash[:notice] = 'Trip Updated' if @trip.update_attributes(params[:trip])
  	respond_with @trip
  end

  def destroy
  	@trip = current_user.trips.find(params[:id])
  	flash[:notice] = 'Trip Destryed' if @trip.destroy
  	redirect_to root_path
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fares_helper.rb
module FaresHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title SeatSeller
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body.container
		%header.row
			#brand.eight.columns.alpha
				%h1 Seat Seller
			%nav.top_nav.eight.columns.omega
				%ul
					%li=link_to 'Find Passengers', new_trip_path
					%li=link_to 'Find a Seat', root_path
					-if current_user
						
						%li= link_to 'Sign Out', sign_out_path, method: :delete
						%li= current_user.email
					-else 
						%li= link_to 'Sign Up', sign_up_path
						%li= link_to 'Sign In', sign_in_path
		-unless flash.empty?
			.flash
				-flash.each do |k, v|
					%p{class: "#{k}"}= "#{v}"
		.main
			= yield

app/views/trips/_fare.html.haml
%li.request
	%div
		%h5= "User: #{fare.email}"
		%p= "Submitted at: #{fare.created_at}"
	.links
		-if can? :approve, fare
			=link_to 'Approve Passenger', fare_path(fare), method: :put, confirm: "Approve this Passenger?"

app/views/trips/_form.html.haml
.form
	=semantic_form_for @trip do |f|
		=f.inputs do 
			=f.input :title
			=f.input :start
			=f.input :destination
			=f.input :available_seats
		=f.actions do 
			=f.action :submit

app/views/trips/_passenger.html.haml
%li.row
	%h5
		=link_to "#{passenger.email}", '#'

app/views/trips/_trip.html.haml
%li.trip
	%h4= trip.title
	%h5= "From #{trip.start} -----> To #{trip.destination}"
	%p= "Available Seats #{trip.available_seats}"
	.row
		%h6.poster
			Posted by: 
			=link_to "#{trip.email}", '#'
		.links
			=link_to 'View Details...', trip_path(trip)
			-if can? :manage, trip
				=link_to 'Edit', edit_trip_path(trip)
				=link_to 'Destroy', trip_path(trip), method: :delete, confirm: "Are you sure?"

app/views/trips/edit.html.haml
%h3 Edit This Trip
=render partial: 'form', object: @trip

app/views/trips/index.html.haml
.row
	%ul.trips.eleven.columns
		=render partial: 'trip', collection: @trips
	%aside.five.columns
		%p look here to see if anyone is going where you are going, and has an extra seat!

app/views/trips/new.html.haml
%h3 Find passengers for your trip!
=render partial: 'form', object: @trip

app/views/trips/show.html.haml
.trip_detail.row
	%h3.title= @trip.title
	.links
		-if can? :request, @trip
			=link_to 'Request Fare', trip_fares_path(@trip), method: :post
		-if can? :manage, @trip
			=link_to 'Edit', edit_trip_path(@trip)
			=link_to 'Destroy', trip_path(@trip), method: :delete, confirm: "Are you sure?"
	%div.eight.columns.alpha
		%h5= "Seats Available: #{@trip.available_seats}"
		%h5= "Time: #{@trip.departure_time}"
	.details.eight.columns.omega
		%h5= "Start: #{@trip.start}"
		%h5= "Destination: #{@trip.destination}"
-if can? :manage, @trip
	.row
		.passengers.eight.columns.alpha
			%h4 Approved Passengers
			%ul
				=render partial: 'passenger', collection: @trip.passengers
		.requests.eight.columns.omega
			%h4 Seat Requests
			%ul
				=render partial: 'fare', collection: @trip.fares.pending